apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-backend-deployment"
  labels:
   project: "{{ .Release.Name }}-project"
spec:
  replicas: {{ .Values.replicas}}
  selector:
    matchLabels:
      project: "{{ .Release.Name }}-project"
  template:
    metadata:
      labels:
        project: "{{ .Release.Name }}-project"
    spec:
      containers:
      - name: "{{ .Release.Name }}-backend-container"
        image: {{ .Values.backend_image}}
        ports:
        - containerPort: {{.Values.backend_container_port}}