apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-frontend-deployment"
  labels:
    app: {{ .Values.app_name}}
spec:
  replicas: {{ .Values.replicas}}
  selector:
    matchLabels:
      project: "{{ .Release.Name }}-project"
  template:
    metadata:
      labels:
        project: "{{ .Release.Name }}-project"
    spec:
      containers:
      - name: "{{ .Release.Name }}-frontend-container"
        image: {{ .Values.frontend_image}}
        ports:
        - containerPort: {{.Values.frontend_container_port}}